### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by joaoeduardo** [wouterj/WouterJEloquentBundle#108]
I would like to use this project, but last commit was in november. Eloquent version is outdated too. Is this project still maintained?

**Comment by wouterj** [comment]
If I'm honest, this project was never maintained. It started as a little "joke" to trigger Symfony people that Laravel isn't that bad, which then turned out to be actually used..

I've never used this bundle in any Symfony application and I don't keep up with the Laravel community, so it's a bit of a weird bundle. Feel free to fork/modify/send PRs to this project. :smiley:
