### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by theofidry** [wouterj/WouterJEloquentBundle#15]
Hi @WouterJ,

I tried to use your bundle for https://github.com/theofidry/EloquentSerializer, see [the test case](https://github.com/theofidry/EloquentSerializer/blob/master/tests/TestCaseTrait.php#L65). But I encounter the following error:

```
ReflectionException: Class config does not exist
```

When trying to do call a `create()` method on my model. Do you have any idea of what may cause this?

Cheers

**Comment by WouterJ** [comment]
I'm not getting any error when running the tests of your project locally. Can you please show what I need to execute to get the error?

(btw, you can also use this bundle for migrations)

**Comment by theofidry** [comment]
Oh that's interesting, I will give it a shot on Travis to see how it goes...

>(btw, you can also use this bundle for migrations)

Good to know although I don't think I'll need it for that project :P

**Comment by WouterJ** [comment]
> Good to know although I don't think I'll need it for that project :P

Well, currently you use artisan for migrations :) It would allow you to get rid of artisan

**Comment by theofidry** [comment]
True but as I have a Laravel application (besides the Symfony one), it doesn't really matter ;)

**Comment by theofidry** [comment]
https://travis-ci.org/theofidry/EloquentSerializer/jobs/142170888 I get the exact same error as locally

**Comment by WouterJ** [comment]
Yeah, I didn't checkout the PR branch. Done that now and I get the error, will investigate.

**Comment by theofidry** [comment]
Cheers

**Comment by WouterJ** [comment]
@theofidry you have to add this line after `static::bootKernel()`:
```php
static::$kernel->getContainer()->get('wouterj_eloquent.initializer')->initialize();
```

The problem is that eloquent needs to be booted. I now do this during the `kernel.request` event, the first hook in the Symfony request cycle as far as I know. As you don't make any requests, you'll have to do this yourself.

If you have a better idea to boot eloquent every time the kernel is booted, I'm very open for suggestions. I would really like to fix it in a better way.

I also discovered a bug in this bundle while executing your tests. I've submitted https://github.com/WouterJ/WouterJEloquentBundle/pull/16 to fix it, will merge and release 0.2.3 when Travis is green.

**Comment by theofidry** [comment]
@WouterJ couldn't this be done in the bundle `boot()` method?

**Comment by WouterJ** [comment]
@theofidry problem is that this method doesn't have access to the container (which is needed to get the capsule instance).

**Comment by theofidry** [comment]
maybe we can use the `console.command` then
