### ISSUE TITLE
`Migrator@requireFiles` definition not compatible with parent

### ISSUE THREAD

**Issue by Whyounes** [wouterj/WouterJEloquentBundle#29]
The method `WouterJ\EloquentBundle\Migrations\Migrator@requireFiles` signature is not compatible with the parent method definition, and this throws a runtime exception. It could be changed to this:

```php
class Migrator extends LaravelMigrator
{
    //...
    public function getMigrationFiles($path)
    {
        $files = Finder::create()->name('*_*.php')->in($path)->sortByName();

        if (0 === count($files)) {
            return [];
        }

        $migrations = [];
        /** @var SplFileInfo $file */
        foreach ($files as $file) {
            $migrations[] = $file->getRealPath();
        }

        return $migrations;
    }

    public function requireFiles(array $files)
    {
        foreach ($files as $file) {
            require_once $file;
        }
    }
}
```

**Comment by wouterj** [comment]
Thanks for another nice report, @Whyounes!

This is because an incompatible version of Laravel is installed (this bundle does not yet support the latest version). In dev-master, it should no longer be possible to do this. After I've released a new version, this bundle will be updated to support the latest versions.
