### ISSUE TITLE
Attempted to call an undefined method named "getStubPath"

### ISSUE THREAD

**Issue by pavliha** [wouterj/WouterJEloquentBundle#41]
when i try to make migration  php app/console eloquent:migrate:make create_flights_table

**Comment by wouterj** [comment]
Thanks for the report!

You seem to have installed this bundle with Laravel 5.4. This is currently not yet supported. This will be fixed by: https://github.com/wouterj/WouterJEloquentBundle/pull/48 Please use `1.0@dev` of this package. This will install Laravel 5.3 for now and Laravel 5.4 as soon as the other PR is merged.

After fixing #6 (which I hope to do today), I'll release 0.4.0.

**Comment by wouterj** [comment]
Unfortunately, a BC break between 5.3 and 5.4 keeps this bundle from supporting both versions. I've now moved Laravel 5.4 support to 0.5.0 (hoping to release 0.4.0 this week).
